name: Ezcontent Decoupled
description: 'Improves Drupal core JSON API experience which supports decoupled apps.'
recipes:
  - ezcontent_content_type
  - ezcontent-blocks-recipe
  - ezcontent-publish-recipe
install:
  - ezcontent_api
  - ezcontent_preview
  - ezcontent_jsonapi_extension

config:
  import:
    decoupled_router: '*'
    jsonapi_boost: '*'
    jsonapi_extras: '*'
    jsonapi_hypermedia: '*'
    openapi_jsonapi: '*'
    openapi_ui_redoc: '*'
    simple_oauth: '*'
    jsonapi: '*'
    access_unpublished: '*'
    tokenuuid: '*'
    ezcontent_api: '*'
    ezcontent_preview: '*'
    ezcontent_jsonapi_extension: '*'



